routes:
- path: ""
  target: $(@D)/index.html
- path: part01
  target: $(@D)/part01.html
- path: css/buttondown.css
  target: resources/buttondown.css

targets:
- path: $(@D)/index.html
  tool: pandoc
  inputs:
  - index.md
  dependencies:
  - .pansite.yaml
  - resources/footer.html
  - resources/header.html
  - resources/nav.html
- path: $(@D)/part01.html
  tool: pandoc
  inputs:
  - part01.md
  dependencies:
  - .pansite.yaml
  - resources/footer.html
  - resources/header.html
  - resources/nav.html

tool-settings:
  pandoc:
    include-in-header-path: resources/header.html
    include-before-body-path: resources/nav.html
    include-after-body-path: resources/footer.html
    number-sections: true
    table-of-contents: true
    template-path: resources/template.html
    vars:
    - [css, css/buttondown.css]
