resolver: lts-7.3
packages:
- .
extra-deps:
- strings-1.1
- text-icu-translit-0.1.0.7
flags: {}
extra-package-dbs: []
extra-lib-dirs:
- /usr/local/opt/icu4c/lib
extra-include-dirs:
- /usr/local/opt/icu4c/include
